# Generated by Django 6.0.3 on 2026-05-09 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="rematch_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="rematch_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rematch_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
