# Generated by Django 5.1.7 on 2026-05-09 09:25

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rematch_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameroom",
            name="board_state",
            field=models.JSONField(default=game.models.default_board_state),
        ),
    ]
